name: Sync Dev to Main

on:
  schedule:
    - cron: '0 6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "lucamauri"
          git config user.email "luca.mauri@gmail.com"

      - name: Checkout main branch
        run: git checkout main

      - name: Merge dev into main
        run: |
          git fetch origin
          git merge origin/dev --no-edit

      - name: Push changes
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
